version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: ucms_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: university_cms
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: ucms_backend
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/university_cms?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build: ./frontend/course-management-ui
    container_name: ucms_frontend
    restart: unless-stopped
    ports:
      - "3002:80"
    depends_on:
      - backend

volumes:
  mysql-data:
    driver: local
