# Railway configuration file for the backend
[build]
commands = ["cd backend && ./mvnw package -DskipTests"]
watchPatterns = ["backend/**"]

[deploy]
startCommand = "cd backend && java -jar target/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
