spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:cmsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://mysql:3306/cmsdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
