# Railway deployment configuration
# This file is for Railway CLI deployment

RAILWAY_DOCKERFILE_PATH=Dockerfile
RAILWAY_DOCKERFILE_INSTALL_COMMAND="npm ci --legacy-peer-deps"
RAILWAY_DOCKERFILE_BUILD_COMMAND="npm run build"
